frequency: 30

sensor_timeout: 0.1

two_d_mode: false

map_frame: map
odom_frame: odom
base_link_frame: base_link

odom0: /agv/odom
odom0_config: [true,  true,  false,
               false, false, false,
               false, false, true,
               false, false, false]
odom0_queue_size: 10
odom0_nodelay: true
odom0_differential: false
odom0_relative: false

imu0: /imu/imu
imu0_config: [false, false, false,
              false, false, true,
              false, false, false,
              true,  false, false]
imu0_queue_size: 10
imu0_nodelay: true
imu0_differential: false
imu0_relative: false

mag0: /imu/mag
mag0_config: [false, false, false,
              false, false, false,
              false, false, false,
              false, false, true]
mag0_queue_size: 10
mag0_nodelay: true
mag0_differential: false
mag0_relative: false

debug: false

