agv_node:
  ros__parameters:
    opencr:
      id: 200
      baud_rate: 1000000
      protocol_version: 2.0

    wheels:
      separation: 0.605
      radius: 0.1

    motors:
      profile_acceleration_constant: 214.577
      profile_acceleration: 0.0

    sensors:
      bumper_1: 0
      bumper_2: 0
      illumination: 0
      ir: 0
      sonar: 0

diff_drive_controller:
  ros__parameters:
    controller:
      left_wheel_name: 'wheel_left_joint'  # Replace with your actual left wheel joint name
      right_wheel_name: 'wheel_right_joint'  # Replace with your actual right wheel joint name

    odometry:
      base_frame_id: 'base_footprint'
      wheel_separation: 0.605
      wheel_radius: 0.1
      publish_rate: 100.0  # Adjust the publish rate as needed
      use_imu: true
      imu0: 'imu_link'  # Replace with your actual IMU link name
      frame_id: 'odom'
      enable_odom_tf: true

