agv_node:
  ros__parameters:
    opencr:
      id: 200
      baud_rate: 1000000
      protocol_version: 2.0

    wheels:
      separation: 0.7
      radius: 0.1

    motors:
      profile_acceleration_constant: 214.577
      profile_acceleration: 0.0

    sensors:
      bumper_1: 0
      bumper_2: 0
      illumination: 0
      ir: 0
      sonar: 0

diff_drive_controller:
  ros__parameters:
    wheel_separation: 0.7
    wheel_radius: 0.1
    command_topic: "cmd_vel"
    publish_odom: true
    publish_odom_tf: true
    publish_wheel_tf: true
    odometry_topic: "/odom"
    odometry_frame: "odom"
    robot_base_frame: "base_link"
    controller_frequency: 50.0  # Adjusted for real-time control (e.g., 100 Hz)

    linear:
      x:
        has_velocity_limits: true
        max_velocity: 0.11  # Adjust to your robot's maximum linear velocity

    angular:
      z:
        has_velocity_limits: true
        max_velocity: 0.25 # Adjust to your robot's maximum angular velocity

    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.001]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.001]
